version: "3.9"

secrets:
  pg_password:
    file: ./pg_password.txt

services:
  db:
    image: postgres:17-alpine
    secrets:
      - pg_password
    container_name: api-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
      POSTGRES_DB: client_database
    volumes:
      - /api-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: db-ui-tool
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9000:8080"